// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:icarus/const/agents.dart';
import 'package:icarus/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AbilityInfoAdapter());
    registerAdapter(AgentTypeAdapter());
    registerAdapter(BoundingBoxAdapter());
    registerAdapter(FreeDrawingAdapter());
    registerAdapter(LineAdapter());
    registerAdapter(MapValueAdapter());
    registerAdapter(OffsetAdapter());
    registerAdapter(PlacedAbilityAdapter());
    registerAdapter(PlacedAgentAdapter());
    registerAdapter(PlacedImageAdapter());
    registerAdapter(PlacedTextAdapter());
    registerAdapter(PlacedUtilityAdapter());
    registerAdapter(PlacedWidgetAdapter());
    registerAdapter(StrategyDataAdapter());
    registerAdapter(StrategySettingsAdapter());
    registerAdapter(UtilityTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AbilityInfoAdapter());
    registerAdapter(AgentTypeAdapter());
    registerAdapter(BoundingBoxAdapter());
    registerAdapter(FreeDrawingAdapter());
    registerAdapter(LineAdapter());
    registerAdapter(MapValueAdapter());
    registerAdapter(OffsetAdapter());
    registerAdapter(PlacedAbilityAdapter());
    registerAdapter(PlacedAgentAdapter());
    registerAdapter(PlacedImageAdapter());
    registerAdapter(PlacedTextAdapter());
    registerAdapter(PlacedUtilityAdapter());
    registerAdapter(PlacedWidgetAdapter());
    registerAdapter(StrategyDataAdapter());
    registerAdapter(StrategySettingsAdapter());
    registerAdapter(UtilityTypeAdapter());
  }
}
