// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:icarus/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AgentTypeAdapter());
    registerAdapter(MapValueAdapter());
    registerAdapter(OffsetAdapter());
    registerAdapter(PlacedAbilityAdapter());
    registerAdapter(PlacedAgentAdapter());
    registerAdapter(PlacedImageAdapter());
    registerAdapter(PlacedTextAdapter());
    registerAdapter(PlacedWidgetAdapter());
    registerAdapter(StrategyDataAdapter());
  }
}
